### ISSUE TITLE
Different repo for Google fonts

### ISSUE THREAD

**Issue by dmklotz** [yixuan/showtext#23] opened 2018-09-07 19:35 UTC
I just tried to use this package today to install Google fonts, but I'm getting this error:

> Error: lexical error: invalid char in json text.
                                       NA
                     (right here) ------^

I checked the documentation for `font_add_google()`, but the default repo is no longer an active site.  Instead of 'http://fonts.gstatic.com', one now has to go to 'http://fonts.google.com', and manually download a font or import it through their API.

**Comment by yixuan** [comment] 2018-09-07 23:31
I think the issue is unrelated to the web address, since the real font file is still using `fonts.gstatic.com`, for example http://fonts.gstatic.com/s/abeezee/v11/esDR31xSG-6AGleN6tI.ttf. If you change it to `fonts.google.com` then there is a 404.

The problem is more like a network issue. I suggest you trying it again.

**Comment by dmklotz** [comment] 2018-09-10 01:46
I think you're right about it being a network issue.  However, while I can connect to the Google API, the function `sysfonts:::google_font_db` as currently written obtains the Google font library from your personal website: https://github.com/yixuan/sysfonts/blob/03380c8e0e92a13789098fdc6c9db55709bc55ee/R/google.R#L30

My work account blocks me from accessing that website, hence the error.  Anyway to restore the direct Google API method, currently commented out in the code?

**Comment by yixuan** [comment] 2018-09-10 16:25
That file was a cache since fetching from Google API is usually slow. I'll add an option to force using the Google API.

**Comment by yixuan** [comment] 2018-10-11 20:42
Fixed in the new release. You can now use the `db_cache = FALSE` option in `font_add_google()`.

**Closed as completed by yixuan** 2018-10-11 20:42 UTC
