### ISSUE TITLE
font not found

### ISSUE THREAD

**Issue by zhouqiangnju** [yixuan/showtext#18] opened 2018-03-28 02:15 UTC
when I use font_add such  as `font_add('fzbs',regular = 'C:/Windows/Fonts/方正小标宋_GBK_0.TTF')`
 to use, there are warnings like this
`warnings()
警告信息：
1: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
  Windows字体数据库里没有这样的字体系列
2: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
  Windows字体数据库里没有这样的字体系列
3: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
  Windows字体数据库里没有这样的字体系列
4: In grid.Call(C_textBounds, as.graphicsAnnot(x$label),  ... :
  Windows字体数据库里没有这样的字体系列`
but this font has already installed in my font library ,and the path is right.
What 's the cause to this problem?Is there any solution?

**Comment by yixuan** [comment] 2018-10-12 17:50
Sorry for the late reply. One thing you can try is to copy the font file to another folder and rename it with only English letters. The Chinese file name may be the cause.

**Comment by yixuan** [comment] 2019-01-11 00:13
Let me close this first unless the problem remains.

**Closed as completed by yixuan** 2019-01-11 00:13 UTC
