### ISSUE TITLE
Can't load showtext

### ISSUE THREAD

**Issue by gpsccs** [yixuan/showtext#30] opened 2020-01-15 07:36 UTC
Hello, when I try to use showtext, it occour the following error:

Error: package or namespace load failed for ‘showtext’:
 loadNamespace()里算'showtext'时.onLoad失败了，详细内容：
  调用(call): utils::unzip(font_file, exdir = out_dir, overwrite = FALSE)
  错误(error): 'exdir' does not exist

How can I fix it?

**Comment by yixuan** [comment] 2020-01-26 13:31
Have you tried to reinstall the package?

**Comment by jinyancool** [comment] 2020-02-02 11:03
I have same errors.

*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘showtext’:
 .onLoad failed in loadNamespace() for 'showtext', details:
  call: file.exists(path)
  error: invalid 'file' argument
Error: loading failed
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
Error: package or namespace load failed for ‘showtext’:
 .onLoad failed in loadNamespace() for 'showtext', details:
  call: file.exists(path)
  error: invalid 'file' argument
Error: loading failed
Error: .onLoad failed in loadNamespace() for 'showtext', details:
  call: file.exists(path)
  error: invalid 'file' argument
** testing if installed package keeps a record of temporary installation path
* DONE (showtext)

**Comment by yixuan** [comment] 2020-04-17 20:29
These issues seem to be related to the write access of temporary directories. Make sure that the folder pointed by `tempdir()` is writable.

**Comment by yihui** [comment] 2020-05-30 20:22
I think @jinyancool's issue is different from @gpsccs's issue. For @jinyancool's issue (reproduced by @XiangyunHuang: https://d.cosx.org/d/419265/3), my guess is that this is not a good idea: https://github.com/yixuan/sysfonts/blob/eae090/R/font.R#L367 The reason is that R will try to load a package from a temporary location when the package is installed. I wonder why you need `lib.loc` at all: https://github.com/yixuan/sysfonts/blob/eae090/R/font.R#L373 It doesn't seem to be necessary to me.

For @gpsccs's issue, you probably need to `dir.create()` the dir first, although it should be rare that the temp dir doesn't exist. If the creation of the dir fails, give users a more informative error message. https://github.com/yixuan/showtextdb/blob/fe105fc/R/load_showtext_fonts.R#L36

**Comment by yixuan** [comment] 2020-05-30 21:23
Thanks for the debugging! I'll create patches later.

**Comment by yixuan** [comment] 2020-05-31 02:15
The problem that @jinyancool encountered was likely due to [these lines](https://github.com/yixuan/showtextdb/blob/fe105fceef4874585dd135c9815e5cd642ca3e66/R/load_showtext_fonts.R#L68-L71).

Inside the `showtextdb/fonts` folder there may exist some font folders such as `source-han-serif-cn`, but somehow the folder does not contain any fonts, and a `NULL` value will be passed to `sysfonts::font_add()`, causing the error above. I'll add more informative messages to the `sysfonts` and `showtextdb` packages.

**Comment by XiangyunHuang** [comment] 2020-05-31 03:19
@yixuan Yeah,  `source-han-serif-cn/` is exist but no fonts, because I failed to install the font before.

**Comment by yixuan** [comment] 2020-05-31 20:22
These issues should have been [fixed by the latest version of the showtextdb package](https://github.com/yixuan/showtextdb/blob/9b0378bb166a2fc30538f65e4e6e5ccaf0928408/inst/NEWS.Rd#L10-L15), which I will submit to CRAN later.

**Comment by yixuan** [comment] 2020-06-04 14:09
The new version of `showtextdb` is on CRAN now.

**Closed as completed by yixuan** 2020-06-04 14:09 UTC
